import { test, expect } from '../fixtures/coverage';
import { ProjectModalPage } from '../pages/ProjectModalPage';
import { BasePage } from '../pages/BasePage';

/**
 * @purpose Validates the end-to-end lifecycle of a project, including creation, editing, and deletion, and ensures proper UI updates and data cleanup.
 */
test.describe('Project Lifecycle @feature-projects', () => {
    let projectModal: ProjectModalPage;
    let basePage: BasePage;

    test.beforeEach(async ({ page }) => {
        projectModal = new ProjectModalPage(page);
        basePage = new BasePage(page);
        await basePage.navigate();
        
        // Ensure we are on the Character Library view (which also lists projects)
        await page.click('#nav-character-library');
    });

    test('creates and deletes a project, verifying IndexedDB cleanup', async ({ page }) => {
        // 1. Create Project
        await projectModal.openNewProjectModal();
        
        const projectName = 'Automated E2E Project';
        const projectDesc = 'This project is generated by automated tests.';
        
        await projectModal.fillProjectDetails(projectName, projectDesc);
        await projectModal.saveProject();

        // 2. Verify Project appears in the UI
        // The projects are rendered in .project-section > .project-header > span
        const projectSection = page.locator('.project-section', { hasText: projectName });
        await expect(projectSection).toBeVisible();

        // 3. Verify IndexedDB State
        await page.waitForTimeout(500); // Buffer for IDB transaction
        const initialAppState = await basePage.evaluateIndexedDBRecords('app_state');
        const projectState: any = initialAppState.find((record: any) => record.key === 'projects');
        expect(projectState).toBeDefined();
        expect(projectState.data.some((p: any) => p.name === projectName)).toBeTruthy();

        // 4. Delete the Project
        // We need to double-click the project title to open the edit modal
        await projectSection.locator('.project-header span').first().dblclick();
        
        page.on('dialog', dialog => dialog.accept()); // Accept the confirmation alert
        await projectModal.deleteProject();

        // 5. Verify Project disappears from UI
        await expect(projectSection).toHaveCount(0);

        // 6. Verify IndexedDB Cleanup
        await page.waitForTimeout(500); // Buffer for IDB transaction
        const finalAppState = await basePage.evaluateIndexedDBRecords('app_state');
        const finalProjectState: any = finalAppState.find((record: any) => record.key === 'projects');
        expect(finalProjectState.data.some((p: any) => p.name === projectName)).toBeFalsy();
    });
});
